language: node_js
node_js:
- 6
- 7
sudo: false
cache:
  directories:
  - node_modules
env:
  global:
    - RELEASE=1039654
    - secure: Plup9c1bK1WW9zAf6YmTHTCaJBdQbGzY8iEAsYtEUsBqDOIQOb3Mzg9zastMqO4KUvY7u0p8ncn6zqv+YdspoGKKZdfiApGjVrSIYLVvcwNWyzFflIKp5BNb4BGHYUUMqcKbSGju+vurQ66GtPxj0bHlMd6zqWjHPZQLMux67E0=
